apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Awesome-Python-Projects"
  title: "Awesome-Python-Projects"
  description: "Github Action to generate Awesome-Python-Projects"
  tags:
    - python
    - python-github
    - github-action
spec:
  type: "github-action"
  owner: "prateek"
  lifecycle: "experimental"
